version: '3.8'
services:
  web-monitor:
      build: .
      image: my-devops-monitor:v1
      environment:
        - TARGET_URL=https://www.google.com
      restart: always  

  url-monitor:
      build: .
      image: my-devops-monitor:v1
      environment:
        - TARGET_URL=https://www.github.com
      restart: always
      


